/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ml.alberto.prototipe.view;

import Users.PBX;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import ml.alberto.prototipe.control.DataBasePBXControl;

/**
 *
 * @author  alberto garcía castro
 */
public class PBXList extends javax.swing.JDialog implements ActionListener {

    private DefaultListModel listaDefecto;
    private DefaultListModel listaDefectoMal;
    private WindowFullAccess full;
    private PBX pbx;
    private ArrayList<String> datas;
    private ArrayList<String> datasMal;
    private DataBasePBXControl control;

    /**
     * Creates new form PBXList
     */
    public PBXList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pbx = new PBX();
        //full = new WindowFullAccess();
        listaDefecto = new DefaultListModel();
        listaDefectoMal = new DefaultListModel();
        PBXMainz.setModel(listaDefecto);
        PBXMalta.setModel(listaDefectoMal);
        datas = new ArrayList<String>();
        datasMal = new ArrayList<String>();
        control = new DataBasePBXControl();

        initList();
        initListMal();
        initButtons();
        añadirDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPXB = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        PBXMainz = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        PBXMalta = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Free PBX Windows");
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        btnInsert.setText("Insert");

        PBXMainz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PBXMainzMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PBXMainz);

        PBXMalta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PBXMalta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PBXMaltaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(PBXMalta);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mainz");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Malta");

        btnDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(btnDelete)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newPXB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnInsert)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(newPXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnDelete)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PBXMainzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PBXMainzMouseClicked
        if (evt.getClickCount() == 2) // Se mira si es doble click
        {
            PBXMainz.clearSelection();

        }
    }//GEN-LAST:event_PBXMainzMouseClicked

    private void PBXMaltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PBXMaltaMouseClicked
        if (evt.getClickCount() == 2) // Se mira si es doble click
        {
            PBXMalta.clearSelection();

        }
    }//GEN-LAST:event_PBXMaltaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBXList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBXList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBXList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBXList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PBXList dialog = new PBXList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> PBXMainz;
    private javax.swing.JList<String> PBXMalta;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField newPXB;
    // End of variables declaration//GEN-END:variables

    public void añadirDatos() {
        datas = pbx.getDatas();

        for (int i = 0; i < datas.size(); i++) {
            if (datas.get(i).charAt(0) == '1') {
                if (listaDefectoMal.isEmpty()) {
                    listaDefectoMal.addElement(datas.get(i));
                } else {
                    listaDefectoMal.insertElementAt(datas.get(i), listaDefectoMal.size());
                }
            } else {
                if (listaDefecto.isEmpty()) {
                    listaDefecto.addElement(datas.get(i));

                } else {
                    listaDefecto.insertElementAt(datas.get(i), listaDefecto.size());
                }
            }
        }

    }

    public JList initList() {
        PBXMainz = new JList(listaDefecto);

        return PBXMainz;
    }

    public JList initListMal() {
        PBXMalta = new JList(listaDefectoMal);
        return PBXMalta;
    }

    public ArrayList<String> returnList() {
        ArrayList<String> pbxList = new ArrayList<String>();
        for (int i = 0; i < listaDefecto.size(); i++) {
            pbxList.add((String) listaDefecto.get(i));
        }
        return pbxList;
    }

    public ArrayList<String> returnListMal() {
        ArrayList<String> pbxListMal = new ArrayList<String>();
        for (int i = 0; i < listaDefectoMal.size(); i++) {
            pbxListMal.add((String) listaDefectoMal.get(i));
        }
        return pbxListMal;
    }

    public void insert() {
        String pbx = newPXB.getText();

        if (pbx.isEmpty()) {
            JOptionPane.showMessageDialog(this, "YOU MUST FILL MAINZ TEXT FIELD");
        } else {
            if (control.verify(pbx)) {
                JOptionPane.showMessageDialog(this, "EXTENSION ALREADY EXIST");

            } else {

                if (pbx.length() > 4) {
                    JOptionPane.showMessageDialog(this, "EXTENSION MUST HAVE ONLY 4 CHARACTERS");
                } else {

                    if (pbx.charAt(0) == '2') {

                        if (!listaDefecto.contains(pbx)) {
                            if (listaDefecto.isEmpty()) {
                                listaDefecto.addElement(pbx);
                                control.insert(pbx);
                                newPXB.setText("");
                            } else {
                                listaDefecto.insertElementAt(pbx, listaDefecto.size());
                                control.insert(pbx);
                                newPXB.setText("");
                            }
                        }
                    } else {
                        if (pbx.charAt(0) == '1') {

                            if (!listaDefectoMal.contains(pbx)) {
                                if (listaDefectoMal.isEmpty()) {
                                    listaDefectoMal.addElement(pbx);
                                    control.insert(pbx);
                                    newPXB.setText("");
                                } else {
                                    listaDefectoMal.insertElementAt(pbx, listaDefectoMal.size());
                                    control.insert(pbx);
                                    newPXB.setText("");
                                }
                            }

                        } else {
                            JOptionPane.showMessageDialog(this, "EXTENSION MUST START FOR 1 OR 2 TO BE CORRECT");
                        }
                    }
                }
            }
        }
    }

    
    public void deleteExtension() {
        if (PBXMainz.getSelectedValue() != null && PBXMalta.getSelectedValue() != null) {
            JOptionPane.showMessageDialog(this, "CHOOSE ONLY ONE EXTENSION");
        } else {

            if (PBXMainz.getSelectedValue() != null && PBXMalta.getSelectedValue() == null) {
                control.delete(PBXMainz.getSelectedValue());
                listaDefecto.clear();
                listaDefectoMal.clear();
                datas.clear();
                JOptionPane.showMessageDialog(this, "ELEMENT DELETE");
                añadirDatos();
            } else {
                if (PBXMainz.getSelectedValue() == null && PBXMalta.getSelectedValue() != null) {
                    control.delete(PBXMalta.getSelectedValue());
                    listaDefectoMal.clear();
                    listaDefecto.clear();
                    datas.clear();
                    JOptionPane.showMessageDialog(this, "ELEMENT DELETE");
                    añadirDatos();
                }
            }

        }

    }

    public void initButtons() {
        btnDelete.addActionListener(this);
        btnInsert.addActionListener(this);
        btnDelete.setActionCommand("DELETE");
        btnInsert.setActionCommand("INSERT");
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();
        switch (command) {
            case "INSERT":
                insert();
                break;
            case "DELETE":
                deleteExtension();
                break;
        }
    }
}
