/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ml.alberto.prototipe.view;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import ml.alberto.prototipe.control.DataBaseOutUsersControl;
import ml.alberto.prototipe.control.TableModel;
import ml.alberto.prototipe.model.User;

/**
 *
 * @author alber
 */
public class TableusersOut extends javax.swing.JFrame implements ActionListener {
         private UserDetails details;
         private ArrayList<User> usersOut;
         private DataBaseOutUsersControl dbout;
          private User userDetails;
    /**
     * Creates new form TableusersOut
     */
    public TableusersOut() {
        initComponents();
        initButons();
        addMouseListener();
         usersOut = new ArrayList<User>();
         dbout = new DataBaseOutUsersControl ();
         userDetails = new User();
         details = new UserDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsersOut = new javax.swing.JTable();
        btnUpgrade = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableUsersOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUsersOut);

        btnUpgrade.setText("Upgrade");

        btnRemove.setText("Remove");

        btnCancel.setText("Cancel");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnUpgrade)
                .addGap(132, 132, 132)
                .addComponent(btnRemove)
                .addGap(143, 143, 143)
                .addComponent(btnCancel)
                .addGap(133, 133, 133)
                .addComponent(jButton4)
                .addGap(142, 142, 142)
                .addComponent(jButton5)
                .addGap(146, 146, 146)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpgrade)
                    .addComponent(btnRemove)
                    .addComponent(btnCancel)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableusersOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableusersOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableusersOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableusersOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableusersOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpgrade;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsersOut;
    // End of variables declaration//GEN-END:variables
    
    
    public void addMouseListener(){
         tableUsersOut.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                try {

                    tableUsersOut = (JTable) e.getSource();
                    Point point = e.getPoint();
                    int row = tableUsersOut.rowAtPoint(point);
                    if (e.getClickCount() == 1) {
                        setUserDetails(new User((String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 0), (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 1), (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 2),
                                (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 3), (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 4), (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 5),
                                (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 6), (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 7), (String) tableUsersOut.getValueAt(tableUsersOut.getSelectedRow(), 8)));

                    }
                } catch (ArrayIndexOutOfBoundsException aio) {
                    System.out.println("EL ARRAY ES MAYOR QUE LA PARTE SELECCIONADA");
                }
            }
        });
    }
    public void initButons(){
        
    }
     public void insertOutOfCompany(){
        try{
            String[] headers = {"ID", "NAME", "LASTNAME", "EMAILML", "MLPASS", "PCPASS", "SKYPEUSER", "BITRIXUSER", "TELEPHONE"};
            String[][] cells;
            usersOut = dbout.recorrerBD();
            cells = new String[usersOut.size()][9];
            for (int i = 0; i < usersOut.size(); i++) {
                cells[i][0] = usersOut.get(i).getId();
                cells[i][1] = usersOut.get(i).getName();
                cells[i][2] = usersOut.get(i).getLastaName();
                cells[i][3] = usersOut.get(i).getEmailML();
                cells[i][4] = "********";
                cells[i][5] = "********";
                cells[i][6] = usersOut.get(i).getSkypeUser();
                cells[i][7] = usersOut.get(i).getBitrixUser();
                cells[i][8] = usersOut.get(i).getTelephone();
            }
             
            TableModel model = new TableModel(cells, headers);
           
        }catch(NullPointerException npe){
            
        }
    }
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public User getUserDetails() {
        return userDetails;
    }

    public void setUserDetails(User userDetails) {
        this.userDetails = userDetails;
    }
}
